#!/usr/bin/env python3
"""generate_hitl_workflow.py

Scaffolds a runnable ADK project implementing a durable, asynchronous
Human-in-the-Loop (HITL) approval gate: an `LlmAgent` with a
`LongRunningFunctionTool` that pauses the invocation, records a pending
ticket, and POSTs a signed state-holding webhook to an external dashboard
-- built on the primitives documented in
references/adk_graph_hitl_api.md and the durability rationale in
references/durable_hitl_patterns.md.

This script only writes text files -- it does not import `google-adk` and
has no third-party dependencies, so `--dry-run` (and even a real run) works
with no ADK install. The GENERATED project does depend on `google-adk` and
`requests` to actually run (see the generated requirements.txt).

The generated project's pending-ticket store uses the exact same JSON shape
`scripts/resume_workflow.py`'s `PendingStore` expects, so the resume side of
the gate is NOT regenerated per-project -- point `resume_workflow.py serve`
(or `resume`) at the generated project's `pending_approvals.json` directly.
This keeps signature verification and resume logic in exactly one place.

Usage:
    generate_hitl_workflow.py --output-dir ./my_approval_agent --dry-run
    generate_hitl_workflow.py --output-dir ./my_approval_agent \\
        --app-name expense_approval_app --tool-name ask_for_approval \\
        --agent-name expense_agent --webhook-url https://dashboard.example.com/hitl/incoming \\
        --secret-env-var HITL_WEBHOOK_SECRET

Exit codes: 0 = success (files written, or dry-run preview printed),
2 = usage error (e.g. output dir already exists and is non-empty).
"""
import argparse
import os
import sys

AGENT_PY_TEMPLATE = '''"""{app_name}: durable HITL approval gate agent.

Generated by adk-durable-human-in-the-loop's generate_hitl_workflow.py.
Grounded in ADK's LongRunningFunctionTool + ResumabilityConfig (see this
skill's references/adk_graph_hitl_api.md) -- re-verify against the current
google-adk release before deploying, this surface is still evolving.
"""
from typing import Any

from google.adk.agents import Agent
from google.adk.apps import App, ResumabilityConfig
from google.adk.tools import LongRunningFunctionTool

from hitl_support import record_ticket_and_notify


def {tool_name}(purpose: str, amount: float, tool_context) -> dict[str, Any]:
    """Ask a human approver for approval before proceeding.

    Call this before finalizing any action that needs sign-off (e.g. a
    spend over the configured threshold). Do NOT block here -- this
    function must return quickly with a 'pending' status; the actual
    approval happens out-of-band via the durable webhook + resume flow.

    Args:
        purpose: Short human-readable description of what is being approved.
        amount: The amount (or other primary quantity) requiring approval.
    """
    # ADK assigns the function_call_id for THIS call; tool_context exposes it
    # via the invocation/function-call machinery. record_ticket_and_notify
    # persists everything needed to resume later and sends the signed
    # webhook -- see hitl_support.py.
    ticket = record_ticket_and_notify(
        tool_context=tool_context,
        tool_name="{tool_name}",
        hint=f"Approve {{purpose}} for {{amount}}?",
        payload={{"purpose": purpose, "amount": amount}},
    )
    return {{
        "status": "pending",
        "ticket-id": ticket["ticket_id"],
        "purpose": purpose,
        "amount": amount,
    }}


{agent_var} = Agent(
    name="{agent_name}",
    model="{model}",
    instruction=(
        "You help process requests that require human approval. "
        "Call {tool_name} before finalizing any action needing sign-off, "
        "then tell the user their request is pending approval -- do not "
        "claim it succeeded until a later turn confirms it."
    ),
    tools=[LongRunningFunctionTool(func={tool_name})],
)

# ResumabilityConfig is required for durable resume across process restarts.
# Pair this with a persistent SessionService in service.py (DatabaseSessionService
# or VertexAiSessionService) -- LongRunningFunctionTool has no documented
# restriction against either, unlike Tool Confirmation (see
# references/adk_graph_hitl_api.md \u00a76).
app = App(
    name="{app_name}",
    root_agent={agent_var},
    resumability_config=ResumabilityConfig(is_resumable=True),
)
'''

HITL_SUPPORT_PY_TEMPLATE = '''"""hitl_support.py: ticket recording + signed webhook dispatch for the
durable HITL approval gate. Generated by generate_hitl_workflow.py.

The pending-ticket JSON shape here matches
adk-durable-human-in-the-loop/scripts/resume_workflow.py's PendingStore
exactly, so that script can be pointed directly at PENDING_STORE_PATH below
to handle the resume side -- do not diverge the field names without also
updating the resume script's expectations (see that skill's
references/durable_hitl_patterns.md \u00a72 and \u00a75).
"""
import hashlib
import hmac
import json
import os
import uuid
from datetime import datetime, timezone

import requests

PENDING_STORE_PATH = os.environ.get("HITL_PENDING_STORE", "./pending_approvals.json")
WEBHOOK_URL = "{webhook_url}"
SECRET_ENV_VAR = "{secret_env_var}"


def _now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _canonical_json(obj):
    return json.dumps(obj, sort_keys=True, separators=(",", ":"))


def _sign(body, secret):
    mac = hmac.new(secret.encode("utf-8"), _canonical_json(body).encode("utf-8"), hashlib.sha256)
    return mac.hexdigest()


def _load_store():
    if not os.path.exists(PENDING_STORE_PATH):
        return {{}}
    with open(PENDING_STORE_PATH) as f:
        return json.load(f)


def _save_store(data):
    tmp = PENDING_STORE_PATH + ".tmp"
    with open(tmp, "w") as f:
        json.dump(data, f, indent=2)
    os.replace(tmp, PENDING_STORE_PATH)


def record_ticket_and_notify(tool_context, tool_name, hint, payload, expires_at=None):
    """Persists a pending-approval record and POSTs the signed state-holding
    webhook. Call this from inside a LongRunningFunctionTool BEFORE
    returning its initial 'pending' result -- never block here waiting for
    the human.

    Idempotency note (references/durable_hitl_patterns.md \u00a74): if ADK
    resumes and re-runs this tool call for the same underlying request
    (at-least-once tool execution on workflow resume), calling this twice
    with the same function_call_id will overwrite the same ticket_id
    (derived deterministically below) rather than creating a duplicate.
    """
    function_call_id = getattr(tool_context, "function_call_id", None) or str(uuid.uuid4())
    invocation_id = getattr(getattr(tool_context, "_invocation_context", None), "invocation_id", None) \\
        or os.environ.get("HITL_DEV_INVOCATION_ID", "unknown-invocation")
    session = getattr(tool_context, "session", None)
    session_id = getattr(session, "id", os.environ.get("HITL_DEV_SESSION_ID", "unknown-session"))
    user_id = getattr(session, "user_id", os.environ.get("HITL_DEV_USER_ID", "unknown-user"))

    ticket_id = f"ticket-{{function_call_id}}"  # deterministic -> idempotent re-record on resume

    record = {{
        "app_name": "{app_name}",
        "user_id": user_id,
        "session_id": session_id,
        "invocation_id": invocation_id,
        "function_call_id": function_call_id,
        "tool_name": tool_name,
        "expires_at": expires_at,
        "resolved": False,
    }}
    store = _load_store()
    store[ticket_id] = record
    _save_store(store)

    secret = os.environ.get(SECRET_ENV_VAR)
    if not secret:
        raise RuntimeError(
            f"{{SECRET_ENV_VAR}} is not set -- refusing to send an unsigned HITL webhook. "
            "Set it to a shared secret only this service and the dashboard know."
        )
    webhook_body = {{
        "ticket_id": ticket_id,
        "app_name": record["app_name"],
        "user_id": user_id,
        "session_id": session_id,
        "invocation_id": invocation_id,
        "function_call_id": function_call_id,
        "tool_name": tool_name,
        "hint": hint,
        "payload": payload,
        "requested_at": _now_iso(),
        "expires_at": expires_at,
        "response_url": None,
    }}
    webhook_body["signature"] = _sign(webhook_body, secret)

    if WEBHOOK_URL:
        try:
            requests.post(WEBHOOK_URL, json=webhook_body, timeout=10)
        except requests.RequestException as e:
            # Do not raise -- the ticket is already durably recorded above;
            # a failed notification is retriable (add your own retry/backoff
            # or a dead-letter queue here for production use), losing the
            # webhook is not the same as losing the pending approval.
            print(f"warning: failed to POST HITL webhook for {{ticket_id}}: {{e}}")
    else:
        print(f"warning: WEBHOOK_URL is empty -- printing webhook payload instead of sending it:")
        print(json.dumps(webhook_body, indent=2))

    return {{"ticket_id": ticket_id}}
'''

SERVICE_PY_TEMPLATE = '''"""service.py: run loop wiring session persistence + pause detection for
{app_name}. Generated by generate_hitl_workflow.py.

Demonstrates the event-watching pattern from
references/adk_graph_hitl_api.md \u00a77: `runner.run_async` returns/streams
normally when a LongRunningFunctionTool pauses -- detect the pause via
`event.long_running_tool_ids`, not by waiting for a final response that
will never come this turn.
"""
import asyncio

from google.adk.runners import Runner
from google.adk.sessions import DatabaseSessionService  # swap for VertexAiSessionService in GCP prod
from google.genai import types

from agent import app

# sqlite for local dev; point at a real Postgres/MySQL DSN in production so
# paused invocations survive a process restart (the entire point of this
# gate -- see references/durable_hitl_patterns.md \u00a71).
session_service = DatabaseSessionService(db_url="sqlite:///./{app_name}_sessions.db")
runner = Runner(app=app, session_service=session_service)


async def start_turn(user_id: str, session_id: str, user_text: str):
    await session_service.create_session(app_name="{app_name}", user_id=user_id, session_id=session_id)
    content = types.Content(role="user", parts=[types.Part(text=user_text)])
    async for event in runner.run_async(user_id=user_id, session_id=session_id, new_message=content):
        if event.long_running_tool_ids:
            print(f"[paused] invocation waiting on tool call(s): {{event.long_running_tool_ids}} "
                  "-- a signed webhook has been sent; resume via resume_workflow.py once approved.")
        elif event.content and event.content.parts:
            text = "".join(p.text or "" for p in event.content.parts)
            if text:
                print(f"[{{event.author}}] {{text}}")


if __name__ == "__main__":
    import sys
    user_id = sys.argv[1] if len(sys.argv) > 1 else "demo-user"
    session_id = sys.argv[2] if len(sys.argv) > 2 else "demo-session"
    prompt = sys.argv[3] if len(sys.argv) > 3 else "Please process a $2500 reimbursement for conference travel."
    asyncio.run(start_turn(user_id, session_id, prompt))
'''

README_TEMPLATE = '''# {app_name}

Generated by `adk-durable-human-in-the-loop`'s `generate_hitl_workflow.py`.
A durable, asynchronous Human-in-the-Loop approval gate built on ADK's
`LongRunningFunctionTool` + `ResumabilityConfig` + `DatabaseSessionService`.

## Files

- `agent.py` -- the `{agent_name}` LlmAgent and its `{tool_name}` approval
  gate tool, wrapped in a resumable `App`.
- `hitl_support.py` -- records a pending ticket and sends the signed,
  state-holding webhook when the gate fires (see the parent skill's
  `references/durable_hitl_patterns.md`).
- `service.py` -- a minimal run loop wiring `DatabaseSessionService` and
  detecting the pause via `event.long_running_tool_ids`.
- `requirements.txt` -- `google-adk`, `requests`.
- `pending_approvals.json` -- created on first run; the durable ticket
  store. Point the parent skill's `resume_workflow.py` at this same path.

## Run it

```bash
pip install -r requirements.txt
export {secret_env_var}="a-long-random-shared-secret"   # never commit this
python service.py demo-user demo-session "Please process a $2500 reimbursement for conference travel."
```

The turn will pause once `{tool_name}` fires and print the ticket ID. A
signed webhook has been POSTed to `{webhook_url_display}` (or printed to
stdout if you left `--webhook-url` empty when generating this project).

## Resume it

Do NOT reimplement signature verification here -- reuse the parent skill's
`resume_workflow.py`, pointed at this project's `pending_approvals.json`:

```bash
# One-shot resume from a decision file (e.g. what your dashboard would send):
python /path/to/adk-durable-human-in-the-loop/scripts/resume_workflow.py resume \\
    --input-file decision.json --pending-store ./pending_approvals.json \\
    --secret-env-var {secret_env_var} --adk-server-url http://localhost:8000

# Or run it as a standing webhook receiver for your dashboard to call:
python /path/to/adk-durable-human-in-the-loop/scripts/resume_workflow.py serve \\
    --pending-store ./pending_approvals.json --secret-env-var {secret_env_var} \\
    --adk-server-url http://localhost:8000 --port 8787
```

`decision.json` must match `assets/approval_response_schema.json` from the
parent skill and be signed with the same `{secret_env_var}` value.

## Production checklist

- [ ] Replace the `sqlite:///` DSN in `service.py` with a real
      Postgres/MySQL DSN so ticket + session state survive a restart.
- [ ] Move `pending_approvals.json` into that same database instead of a
      flat file (see `references/durable_hitl_patterns.md` \u00a72).
- [ ] Set an `expires_at` when calling `record_ticket_and_notify` and wire
      a scheduler for re-notification/escalation (\u00a76 of that reference --
      not implemented by this generator).
- [ ] Put `resume_workflow.py serve` behind your real ingress/auth layer;
      it is a reference implementation, not a production-hardened server.
'''

REQUIREMENTS_TEMPLATE = "google-adk>=2.0.0\nrequests>=2.31\n"


def render(output_dir, args):
    files = {
        "agent.py": AGENT_PY_TEMPLATE.format(
            app_name=args.app_name, tool_name=args.tool_name,
            agent_name=args.agent_name, agent_var=args.agent_name.replace("-", "_"),
            model=args.model,
        ),
        "hitl_support.py": HITL_SUPPORT_PY_TEMPLATE.format(
            webhook_url=args.webhook_url, secret_env_var=args.secret_env_var,
            app_name=args.app_name,
        ),
        "service.py": SERVICE_PY_TEMPLATE.format(app_name=args.app_name),
        "README.md": README_TEMPLATE.format(
            app_name=args.app_name, agent_name=args.agent_name, tool_name=args.tool_name,
            secret_env_var=args.secret_env_var,
            webhook_url_display=args.webhook_url or "(none configured -- payload printed to stdout)",
        ),
        "requirements.txt": REQUIREMENTS_TEMPLATE,
    }
    return files


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--output-dir", required=True, help="Directory to create/populate (must not already exist)")
    ap.add_argument("--app-name", default="hitl_approval_app")
    ap.add_argument("--agent-name", default="approval_agent")
    ap.add_argument("--tool-name", default="ask_for_approval")
    ap.add_argument("--model", default="gemini-flash-latest")
    ap.add_argument("--webhook-url", default="",
                     help="Where to POST the signed state-holding webhook. Empty = print to stdout instead.")
    ap.add_argument("--secret-env-var", default="HITL_WEBHOOK_SECRET",
                     help="Name of the env var holding the HMAC signing secret (never the secret value itself)")
    ap.add_argument("--dry-run", action="store_true", help="Print the file tree and previews; write nothing")
    args = ap.parse_args()

    for name in (args.app_name, args.agent_name, args.tool_name):
        if not name.isidentifier():
            print(f"error: {name!r} must be a valid Python identifier "
                  "(used as a module-level name in the generated code)", file=sys.stderr)
            sys.exit(2)

    files = render(args.output_dir, args)

    if args.dry_run:
        print(f"Would create {args.output_dir}/ with:")
        for name, content in files.items():
            print(f"  {name}  ({len(content.splitlines())} lines)")
        print("\nDry run only -- no files written. Re-run without --dry-run to generate the project.")
        sys.exit(0)

    if os.path.exists(args.output_dir) and os.listdir(args.output_dir):
        print(f"error: '{args.output_dir}' already exists and is not empty -- refusing to overwrite", file=sys.stderr)
        sys.exit(2)

    os.makedirs(args.output_dir, exist_ok=True)
    for name, content in files.items():
        with open(os.path.join(args.output_dir, name), "w") as f:
            f.write(content)
    print(f"Generated {len(files)} file(s) in {args.output_dir}/")
    print("Next: cd into it, `pip install -r requirements.txt`, set the secret env var, and see README.md")
    sys.exit(0)


if __name__ == "__main__":
    main()
